### ISSUE TITLE
Не меняется count в ответе на запросы с фильтрацией

### ISSUE THREAD

**Issue by SonyaPolityko** [Pets-for-Juniors/backend#35]
**Описание:** при отправке запроса на фильтрацию животных в ответе count = 20
**Шаги воспроизведения:**

1. Отправить запрос на https://pets-for-juniors.azurewebsites.net/api/pets/?type=dog, сравнить значение count с фактическим
2. Отправить запрос на https://pets-for-juniors.azurewebsites.net/api/pets/?type=cat&sex=male,  сравнить значение count с фактическим
3. Отправить запрос на https://pets-for-juniors.azurewebsites.net/api/pets/?age__gte=0&age__lte=2&breed=%D0%9D%D0%B5%D0%BC%D0%B5%D1%86%D0%BA%D0%B0%D1%8F%20%D0%BE%D0%B2%D1%87%D0%B0%D1%80%D0%BA%D0%B0,  сравнить значение count с фактическим

**Ожидаемый результат:** количество count равно количеству животных, соответствующих фильтрам
**Фактический результат:** вне зависимости от выбранных фильтров, в ответе count = 20, даже если нет ни одного животного, подходящего под фильтры

**Скрины ошибки:**
![Image](https://github.com/user-attachments/assets/c1a26585-d0d2-46a2-aee6-c6b848f05916)

![Image](https://github.com/user-attachments/assets/773dd822-f54f-4a72-94c9-7b6cea515b31)

![Image](https://github.com/user-attachments/assets/0b50710e-0441-498c-ae66-db82fd8740db)

![Image](https://github.com/user-attachments/assets/dc1d8ad5-d412-4991-9e02-80b6fa44e621)

**Comment by MasterOfHell666** [comment]
Count должен меняться ТОЛЬКО при наличии фильтров, наличие offset и limit НЕ должно влиять на значение Count.

Эти два запроса должны иметь ОДИНАКОВЫЕ Count:
https://pets-for-juniors.azurewebsites.net/api/pets/?limit=2
https://pets-for-juniors.azurewebsites.net/api/pets

Эти два запроса должны иметь РАЗНЫЕ Count:
https://pets-for-juniors.azurewebsites.net/api/pets/?sex=male
https://pets-for-juniors.azurewebsites.net/api/pets
